## R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

before_install:
  Rscript -e 'update.packages(ask = FALSE)'

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github(ssh_id = Sys.getenv("TRAVIS_DEPLOY_KEY", ""))'
  skip_cleanup: true
  
addons:
  apt:
    packages:
    - libudunits2-dev
    - libproj-dev
    - libgeos-dev
    - libgdal-dev
    - libnetcdf-dev

matrix: # don't test osx + r-devel
  include:
  - os: linux
    r: release
    dist: trusty
  - os: linux
    r: devel
    dist: trusty
  - os: osx
    r: release
  - os: osx
    r: oldrel

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'

